# Generated by Django 3.1.1 on 2020-09-22 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0005_auto_20200922_0922'),
        ('company', '0002_auto_20200922_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('is_am', models.BooleanField()),
                ('count_car', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('count_location', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('car_number', models.PositiveIntegerField()),
                ('car_index', models.PositiveIntegerField()),
                ('json_map', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='customer.order')),
                ('route_m', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='delivery.routem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
