# Generated by Django 3.1.1 on 2020-09-23 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_order_is_am'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routed',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.customer'),
        ),
    ]
