# Generated by Django 3.1.1 on 2020-09-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20200923_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routed',
            old_name='order',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='routed',
            old_name='car_index',
            new_name='route_index',
        ),
        migrations.RenameField(
            model_name='routed',
            old_name='car_number',
            new_name='route_number',
        ),
        migrations.AlterField(
            model_name='routem',
            name='date',
            field=models.DateField(),
        ),
    ]
