# Generated by Django 3.1.1 on 2020-09-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_mutualdistance_json_map'),
        ('delivery', '0004_auto_20200923_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='routed',
            name='orders',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='customer.order'),
            preserve_default=False,
        ),
    ]
