# Generated by Django 3.1.1 on 2020-09-29 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_routed_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routed',
            name='orders',
        ),
    ]
