# Generated by Django 3.1.1 on 2020-10-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_routed_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routem',
            options={'ordering': ['details__route_index', 'details__route_number']},
        ),
    ]
