# Generated by Django 3.1.1 on 2020-10-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20201005_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routem',
            options={},
        ),
    ]
