# Generated by Django 3.1.1 on 2020-10-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20201005_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='routed',
            name='distance',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
