# Generated by Django 3.1.1 on 2020-10-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_routed_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routed',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
