# Generated by Django 3.1.1 on 2020-11-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_driver'),
        ('delivery', '0014_auto_20201111_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routed',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.driver'),
        ),
    ]
