# Generated by Django 3.1.1 on 2020-11-12 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_driver_course_number'),
        ('delivery', '0016_auto_20201111_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routed',
            name='driver',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='company.driver'),
        ),
    ]
