# Generated by Django 3.1.1 on 2020-09-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200921_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MutualDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('distance', models.PositiveIntegerField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.customer')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
