# Generated by Django 3.1.1 on 2020-09-22 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200922_0834'),
        ('customer', '0005_auto_20200922_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='company.company'),
            preserve_default=False,
        ),
    ]
