# Generated by Django 3.1.1 on 2020-09-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_am',
            field=models.BooleanField(default=True),
        ),
    ]
