# Generated by Django 3.1.1 on 2020-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_order_is_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualdistance',
            name='json_map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
