# Generated by Django 3.1.1 on 2020-09-29 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20200929_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='route',
        ),
    ]
