# Generated by Django 3.1.1 on 2020-09-29 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_remove_routed_orders'),
        ('customer', '0015_remove_order_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.routed'),
        ),
    ]
