# Generated by Django 3.1.1 on 2020-11-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='course_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
