# Generated by Django 3.1.1 on 2020-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_driver_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='push_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
